### ISSUE TITLE
feat: multi device sync via self hosted server

### ISSUE THREAD

**Issue by maytees** [maytees/shelf#4]
Add support for syncing Shelf commands across multiple devices through a self hosted server solution. This would allow users to maintain a consistent command _shelf_ across all their machines.

# Core features

## Server

- Self hostable
- Written preferably with GO, possibly Deno
- RESTful API endpoints:
  - Command Syncing (push/pull)
  - User auth
  - Collection management
  - Shared collections? (multiplayer shelf!)

In terms of storage, there would be two files for storage, the local storage file and the server's file.

### Additional server features

1. Shared Collections
  - Shared command collections with other users
  - Permission levels (read/write)
2. Integration with #3

## Config (local)

```toml
[server]
url = "http://localhost:6789"
auth_token = "user_token"
auto_sync = true # Syncs automatically every time the shelf command is run
```

## New commands

- `shelf sync` - Manual sync with server
- `shelf server` - Subcommand for server operations
  - `shelf server status` - Returns health check from server
